"""add sla fields

Revision ID: 1b19ddcbf8c4
Revises: ff38158f5a61
Create Date: 2026-05-15 00:34:51.949469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b19ddcbf8c4'
down_revision: Union[str, Sequence[str], None] = 'ff38158f5a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'incidents',
        sa.Column(
            'sla_breached',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'sla_breached')
    op.drop_column('incidents', 'notified_at')
    op.drop_column('incidents', 'sla_deadline')
    # ### end Alembic commands ###
