"""initial_migration

Revision ID: ff38158f5a61
Revises: 
Create Date: 2026-05-10 21:41:33.047044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff38158f5a61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('category', sa.Enum('PAYMENT', 'AUTH', 'DATABASE', 'NETWORK', 'PERFORMANCE', 'UNKNOWN', name='incidentcategory'), nullable=True))
    op.add_column('incidents', sa.Column('suggested_fix', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('ai_notes', sa.Text(), nullable=True))
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('incidents', 'ai_notes')
    op.drop_column('incidents', 'suggested_fix')
    op.drop_column('incidents', 'category')
    # ### end Alembic commands ###
